
spring:
  application:
    name: mslocadora
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
