
spring:
  application:
    name: mslocadora
  datasource:
    url: jdbc:postgresql://dpg-co45bun79t8c738uvgqg-a.oregon-postgres.render.com:5432/locadora_ncgd
    username: locadora_ncgd_user
    password: ivXnkbz179AsDEmgWNz7jE6exKJ73mMu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

